[tool.poetry]
name = "crawler"
version = "0.1.0"
description = ""
authors = ["John Syrinek <john.syrinek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scrapy = "^2.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
