name: image-processing
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - scikit-image
  - pip
  - numpy
  - astropy
  - requests
  - pip:
    - photutils
    - drizzle
    - pyvo
    - parallel-pandas
    - opencv-python-headless
